version: '3.2'
volumes:  
  grafana_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,rw,nolock,hard"
      device: ":/multimedia/projectAutomata/prometheus/grafana"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    links:
      - cadvisor:cadvisor
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
     - "/home/murtaza/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    depends_on:
    - cadvisor-1
    - cadvisor-2
    restart: always
    
  cadvisor-1:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor-1
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    depends_on:
    - redis
    restart: always
  cadvisor-2:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor-2
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    depends_on:
    - redis
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    restart: always

  node-exporter-1:
    container_name: node-exporter-1
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always

  node-exporter-2:
    container_name: node-exporter-2
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9200:9100
    restart: always
    
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "/home/murtaza/prometheus/alertmanager/:/etc/alertmanager/"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3100:3000
    volumes:
      - "/home/murtaza/prometheus/grafana/config/:/var/lib/grafana/"
      - "/home/murtaza/prometheus/grafana/provisioning/:/etc/grafana/provisioning/"
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
    user: "472"
    restart: always